# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '* * * * 3'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  set-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python get_gfwlist.py

      - name: push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update ${{ steps.timestamp.outputs.TIMESTAMP }}
